import {
  AlertTriangle,
  Award,
  Briefcase,
  Building2,
  Calendar,
  ClipboardCheck,
  Cog,
  Cpu,
  FileSignature,
  FileText,
  Folder,
  Globe,
  Headset,
  Key,
  Layers,
  Lock,
  Megaphone,
  Palette,
  Rocket,
  Scale,
  Server,
  Shield,
  ShieldCheck,
  Target,
  Users,
  Wallet,
  Wrench,
  type LucideIcon,
  type LucideProps,
} from 'lucide-react';

/** Íconos disponibles para áreas y tipos de solicitud (se guardan por clave en la BD) */
export const ICONS: Record<string, LucideIcon> = {
  folder: Folder,
  'file-text': FileText,
  'shield-check': ShieldCheck,
  shield: Shield,
  scale: Scale,
  cpu: Cpu,
  users: Users,
  cog: Cog,
  headset: Headset,
  megaphone: Megaphone,
  lock: Lock,
  server: Server,
  'clipboard-check': ClipboardCheck,
  'file-signature': FileSignature,
  wrench: Wrench,
  key: Key,
  award: Award,
  calendar: Calendar,
  wallet: Wallet,
  palette: Palette,
  alert: AlertTriangle,
  briefcase: Briefcase,
  building: Building2,
  globe: Globe,
  layers: Layers,
  target: Target,
  rocket: Rocket,
};

export function Icon({ name, ...p }: { name?: string } & LucideProps) {
  const C = ICONS[name || 'folder'] || Folder;
  return <C {...p} />;
}
